package:
  name: metview
  version: "4.8.7"

source:
  url: https://software.ecmwf.int/wiki/download/attachments/3964985/Metview-4.8.7-Source.tar.gz
  md5: 79ebe622c3d6480f3940d524f21db302

build:
  number: 0

requirements:
  build:
    - qt
    - gdbm
    - imagemagick
    - proj4
    - hdf5
    - netcdf-cxx-legacy
    - netcdf4
    - curl
    - bison
    - flex
    - eccodes 2.5.0
    - eccodes-fortran 2.5.0 gfortran485*
    - libemos 4.5.1 gfortran485*
    - magics 2.34.1 metview*
    - gcc 4.8.5

  run:
    - qt
    - gdbm
    - imagemagick
    - proj4
    - hdf5
    - netcdf-cxx-legacy
    - netcdf4
    - curl
    - bison
    - flex
    - eccodes 2.5.0
    - eccodes-fortran 2.5.0 gfortran485*
    - libemos 4.5.1 gfortran485*
    - magics 2.34.1 metview*
    - gcc 4.8.5
    - libgcc 4.8.5
    - libgfortran 3.0.0

about:
  home: https://software.ecmwf.int/wiki/display/METV/Metview
  license: Apache License 2.0
